name: Build and Deploy to Github Pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        wasm-pack-version: [latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Use Wasm-Pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: ${{ matrix.wasm-pack-version }}
      - name: Build Rust src into wasm
        working-directory: src
        run: wasm-pack build

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build node
        working-directory: web
        run: |
          npm install
          npm run build

      - name: Checkout page repository
        uses: actions/checkout@v2
        with:
          repository: hunomina/epidemic-simulator.page
          token: ${{ secrets.DEPLOY_TO_PAGES_PAT }}
          path: page-repo

      - name: Push to page repository
        working-directory: page-repo
        run: |
          git config user.name hunomina
          git config user.email hugo.f972@gmail.com
          cp ../web/dist/* ./
          git add .
          git commit -m "Deploy to page (from $GITHUB_SHA)"
          git push
